import type { Metadata } from "next";
import "./globals.css";
import { Bebas_Neue, Montserrat } from "next/font/google";
import 'remixicon/fonts/remixicon.css'

const bebasNeue = Bebas_Neue({
  weight: "400", // only one weight available
  subsets: ["latin"],
  variable: "--font-bebas-neue",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Professor Portfolio - Dr. Altaf Hussain Samo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`${bebasNeue.variable} ${montserrat.variable} font-montserrat`}>
        {children}
      </body>
    </html>
  );
}
